version: "3.8"

services:
  postgres:
    image: "postgres:12.2"
    environment:
      - POSTGRES_PASSWORD=postgres
    volumes:
      - postgres:/var/lib/postgresql/data

  redis:
    image: 'redis:3.2-alpine'
    command: redis-server
    ports:
      - '6379:6379'
    volumes:
      - 'redis:/var/lib/redis/data'

  app:
    build: .
    command: bash start.sh
    ports:
      - "3000:3000"
    environment:
      - DB_PASSWORD=postgres
    volumes:
      - .:/onebitchat
      - gems:/gems
    depends_on:
      - postgres
      - redis

volumes:
  postgres:
  redis:
  gems: