default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  host: postgres
  user: postgres
  password: <%= ENV['DB_PASSWORD'] %>

development:
  <<: *default
  database: onebitchat_development

test:
  <<: *default
  database: onebitchat_test

production:
  <<: *default
  database: onebitchat_production
  username: onebitchat
  password: <%= ENV['ONEBITCHAT_DATABASE_PASSWORD'] %>
